name: legion
description: Dead-Simple Cross Compilation
version: 0.1.0
dependencies:
  legit:
    git: https://github.com/DirectMyFile/legit.git
  path: "^1.3.9"
  dye: "^0.0.2"
  system_info: "^0.0.16"
  args: "^0.13.7"
  mustache: "^0.2.5+1"
executables:
  legion:
