name: legion
description: Dead-Simple Cross Compilation
version: 0.0.1
dependencies:
  legit:
    git: https://github.com/DirectMyFile/legit.git
  path: "^1.3.9"
  prompt: "^0.1.7"
  dye: "^0.0.2"
  system_info: "^0.0.16"
executables:
  legion:
